services:
  - type: web
    name: telegram-bot-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: PORT
        value: 5000
